const CardData = [
  {
    //done
    id: 1,
    imgPath: "/Assets/Images/AbhishekAppaji.jpg",
    name: "Abhishek Appaji?",
    text: "Abhishek obtained my Bachelor of Engineering in Medical Electronics with University Rank from BMSCE, India, and a Masters of Engineering (M.E) in Bioinformatics from University Visvesvaraya College of Engineering, India. His Ph.D. was in Mental Health and Neurosciences from Maastricht University, the Netherlands which received the Best thesis award. He is currently working as Assistant Professor in the department of Medical Electronics, BMSCE, India, and aspiring to join as a Post-doc at Ohio State University, USA.  ",
    websitePath: "https://linkedin.com/in/abhishek-appaji/",
    linkText: "LinkedIn",
    websitePath1: "",
    linkText1: "",
    email: "abhishek6675@gmail.com",
    phone: "",
  },
  {
    id: 2,
    imgPath: "/Assets/Images/JoseLuisAmbite.jpeg",
    name: "Jose-Luis Ambite",
    text: "Jose-Luis Ambite, PhD, is an Associate Research Professor of Computer Science, and a Research Team Leader at the Information Sciences Institute,  at the University of Southern California. He is an expert on information integration, including schema mapping, record linkage, efficient query rewriting, and information extraction. His research interests span databases, knowledge representation, semantic web, Federated Learning, and biomedical data science.",
    websitePath: "www.isi.edu/~ambite",
    linkText: "Personal Profile",
    websitePath1: "",
    linkText1: "Button Text2",
    email: "ambite@ads.isi.edu",
    phone: "310-448-8472",
  },
  {
    id: 3,
    imgPath: "/Assets/Images/DanielMarcus.jpeg",
    name: "Daniel Marcus",
    text: "Dr. Marcus’ laboratory builds imaging informatics and analysis tools, with a particular focus on neuroimaging. The laboratory has developed the XNAT imaging informatics platform (www.xnat.org), open source software used in facilities around the world to manage and share neuroimaging and related data. Dr. Marcus directs a number of service cores at the University, including for the Alzheimer’s Disease Research Center, the Intellectual Developmental Disabilities Research Center, and NINDS Center Core for Brain Imaging. He’s also an investigator in several NIH-backed initiatives to develop a national informatics infrastructure, including the Biomedical Informatics Research Network (BIRN), the National Alliance for Medical Image Computing (NAMIC), and Informatics for Integrating Biology and the Bedside (I2B2).",
    websitePath:
      "https://www.mir.wustl.edu/research/research-support-facilities/neuroimaging-informatics-analysis-center-niac/our-staff/niac-staff-dan-marcus",
    linkText: "Button Text",
    websitePath1: "",
    linkText1: "Button Text2",
    email: "dmarcus@wustl.edu",
    phone: "",
  },
  {
    id: 4,
    imgPath: "/Assets/Images/WillHorton.jpeg",
    name: "Will Horton",
    text: "This is a quick bio of Will",
    websitePath: "https://www.isi.edu/~ambite/",
    linkText: "Button Text",
    websitePath1: "",
    linkText1: "Button Text2",
    email: "hortonw@wustl.edu",
    phone: "",
  },
  {
    id: 5,
    imgPath: "/Assets/Images/HowardLander.png",
    name: "Howard Lander",
    text: `Mr. Lander joined the Renaissance Computing Institute in April 2005 and has worked extensively here with the application of Cyber Science and Engineering to data intensive scientific disciplines including neuroscience, physical oceanography and evolutionary biology. In particular Mr. Lander was an active participant in both the Southeastern Universities Research Association (SURA) Coastal Ocean Observing and Prediction Program (SCOOP) and North Carolina Flood Mapping (NCFMP) projects. Mr. Lander is currently a Co-PI on the NeuroBridge, a NIDA funded project whose goals are to increase the discoverability of relevant data in the neurosciences. From 2012 to 2015, Mr. Lander was a Co-PI on the DataBridge project, an NSF funded research effort investigating the use of sociometric techniques to produce a Facebook like social network for data sets from the long tail of science. From 2016 to 2017 Mr. Lander was a CO-PI on the DataBridge for NeuroScience project, an NSF funded follow-up to the DataBridge. As part of this project, Mr. Lander chaired the INCF 2018 Workshop on Advanced Data Discovery for Neuroscience which occurred at INCF’s Neuroinformatics 2018 meeting.`,
    websitePath: "",
    linkText: "Button Text",
    websitePath1: "",
    linkText1: "Button Text2",
    email: "howard@renci.org",
    phone: "",
  },
  {
    //done
    id: 6,
    imgPath: "/Assets/Images/JanineBijsterbosch.jpeg",
    name: "Janine Bijsterbosch",
    text: "Dr. Bijsterbosch’s research focuses on functional brain networks to investigate brain connectivity from three different angles: Firstly, Dr. Bijsterbosch uses population datasets such as the UK Biobank to study individual differences in brain connectivity and their potential to predict risk and resilience to mental health disorders such as depression. Secondly, Dr. Bijsterbosch works on methodological challenges in relation representing high-dimensional resting state functional MRI data into a lower dimensional set of features that are sensitive and interpretable. Thirdly, Dr. Bijsterbosch performs cross-scale research in collaboration with Dr. Larry Snyder to determine how large-scale networks observed with functional MRI behave at the level of individual neural cells.",
    websitePath: "https://profiles.wustl.edu/en/persons/janine-bijsterbosch",
    linkText: "Personal Profile",
    websitePath1: "https://sites.wustl.edu/personomics/",
    linkText1: "Lab Website",
    email: "janine.bijsterbosch@wustl.edu",
    phone: "",
  },
  {
    id: 7,
    imgPath: "/Assets/Images/RickHerrick.jpeg",
    name: "Rick Herrick",
    text: "Raised in the Deep South (Tampa), Rick was moved to California by the Air Force, where he adapted well to the mild weather. He graduated from U.C. Santa Cruz (go Slugs!) with a degree in Politics. He met his future wife Carrie while attending Avocado Sundae shows. They got married, had a daughter and named her Lucie, moved to Long Beach, CA, hated the L.A. traffic, and now reside in Webster Groves, MO. Rick drives a Jeep Wrangler, plays guitar and mandolin, has three dogs and a cat, and favors the “ribs” food group. Rick has worked for Washington University in St. Louis for 10 years and is the lead developer and architect for the open-source XNAT imaging informatics platform.",
    websitePath: "https://www.xnat.org",
    linkText: "XNAT",
    websitePath1: "",
    linkText1: "Button Text2",
    email: "jrherrick@wustl.edu",
    phone: "",
  },
  {
    //done
    id: 8,
    imgPath: "/Assets/Images/JessicaTurner.jpeg",
    name: "Jessica Turner",
    text: `I am investigating the genetics underlying brain structure changes in chronic schizophrenia, as well as the genetic influences on functional and structural neuroimaging measures in other neuropsychological diseases. The first research program includes the extraction and understanding of multivariate patterns within the combined methods of neuroimaging and genetics, as applied to clinical populations. I primarily use independent component analysis (ICA), as well as its extensions into multi-modal datasets.  My background is in psychophysics and MRI methodology as applied to a range of clinical populations, with secondary experience in the analysis of genome wide scan (GWS) data. I collaborate closely with psychiatrists, computer scientists, geneticists and neuroscientists in research on the genetics of brain function and dysfunction. `,
    websitePath: "http://psychology.gsu.edu/profile/jessica-turner/",
    linkText: "Personal Profile",
    websitePath1: "",
    linkText1: "",
    email: "jturner63@gsu.edu",
    phone: "404-413-6211",
  },
  {
    id: 9,
    imgPath: "/Assets/Images/AlexKogan.jpg",
    name: "Alex Kogan",
    text: "Clinical and medical research information organization, transmission and storage, effective use of healthcare electronic standards.",
    websitePath: "",
    linkText: "Button Text",
    websitePath1: "",
    linkText1: "Button Text2",
    email: "kogan.33@osu.edu",
    phone: "",
  },
  {
    id: 10,
    imgPath: "/Assets/Images/LeiWang.jpg",
    name: "Lei Wang, PhD",
    text: "Dr. Lei Wang's lab research is focused on the development of multidimensional and multimodal neuroimaging biomarkers using the tools of computational anatomy. Working with collaborators from engineering, mathematics, psychology and clinical specialties, the team focuses on the following major areas: Mapping of Brain Structures using MRI. Dr. Wang develops automated pipelines to delineate brain structures based on simultaneous mappings of multiple structures from multiple atlases. This includes deep brain structures (such as the hippocampus, amygdala, thalamus, and basal ganglia) and cortical structures.Complex Neuroimaging Biomarkers. They develop modeling and statistical approaches for the analysis of these maps and frameworks for joint, integrated analyses of multidimensional, multimodal information based on the structural mapping of the brain.",
    websitePath: "http://niacal.northwestern.edu/",
    linkText: "Research",
    websitePath1: "",
    linkText1: "Button Text2",
    email: "lei.wang@osumc.edu",
    phone: "",
  },
  {
    id: 11,
    imgPath: "",
    name: "Stephen M. Moore",
    text: "This is a quick bio of Stephen M. Moore",
    websitePath: "https://icts.wustl.edu/people/stephen-m-moore-ms/",
    linkText: "Button Text",
    websitePath1: "",
    linkText1: "Button Text2",
    email: "moore.stephen.m@wustl.edu",
    phone: "",
  },
  {
    id: 12,
    imgPath: "",
    name: "Matthew Turner",
    text: `Matthew Turner is a research scientist in the department of psychology at Georgia State University. His current research focuses on automated text processing and machine learning in scientific literature analysis, meta-analysis of large scale data sets, "moral injury" in civilian populations, electrophysiological signatures of altered states of consciousness (such as meditation and hypnosis), and beliefs in unusual personal experiences. His prior work has been in acoustics and the psychology of hearing, signal processing, and computational science.`,
    websitePath: "",
    linkText: "Button Text",
    websitePath1: "",
    linkText1: "Button Text2",
    email: "mturner46@gsu.edu",
    phone: "",
  },
  {
    id: 13,
    imgPath: "/Assets/Images/PetraLenzini.jpg",
    name: "Petra Lenzini, MS",
    text: "Petra Lenzini is a Research Statistician with the Mallinckrodt Institute of Radiology at Washington University School of Medicine in St. Louis.  As part of the Connectome Coordination Facility. She works closely with NIMH Data Archive Curators, XNAT developers, and Clinical Research partners to clean, shape, move, and facilitate public access to complex research datasets.",
    websitePath: "",
    linkText: "Button Text",
    websitePath1: "",
    linkText1: "Button Text2",
    email: "plenzini@wustl.edu",
    phone: "",
  },
  {
    id: 14,
    imgPath: "/Assets/Images/SatyaSahoo.jpeg",
    name: "Satya Sahoo, PhD",
    text: "Dr. Satya S. Sahoo’s research is focused on developing new data and metadata representation and analysis techniques for biomedical and healthcare research. Dr. Sahoo has led the development of four ontologies in multiple domains, including one for complex neurological disorders, such as epilepsy. Using the Epilepsy and Seizure Ontology (EpSO), his group is focused on the analysis of brain connectivity data for characterizing epilepsy seizure networks using novel computational approaches. To address the challenges of data quality and scientific reproducibility in data-driven biomedical research, Dr. Sahoo and his group are also developing a comprehensive framework for provenance metadata using provenance ontology and text mining of all 1.6 million full-text published articles from NCBI PubMed Central.",
    websitePath:
      "https://case.edu/medicine/pqhs/about/people/primary-faculty/satya-sahoo-phd",
    linkText: "Button Text",
    websitePath1: "",
    linkText1: "Button Text2",
    email: "satya.sahoo@case.edu",
    phone: "216-368-3286",
  },
  {
    //done
    id: 15,
    imgPath: "/Assets/Images/ArcotRajasekar1.jpeg",
    name: "Arcot Rajasekar",
    text: "Dr. Arcot Rajasekar is a Professor at the UNC School of Information and Library Science (SILS) and a Chief Scientist at the Renaissance Computing Institute(link is external) (RENCI). Previously he was at the San Diego Supercomputer Center at the University of California, San Diego, leading the Data Grids Technology Group. He has been involved in research and development of data grid middleware systems for over a decade and is a lead originator behind the concepts in the Storage Resource Broker (SRB) and the integrated Rule Oriented Data Systems (iRODS)(link is external), two premier data grid middleware developed by the Data Intensive Cyber Environments (DICE) Group.A leading proponent of policy-oriented, large-scale data management, Dr. Rajasekar has several research projects funded by the National Science Foundation, the National Archives, National Institute of Health and other federal agencies. He has more than 150 publications in the areas of data grids, digital library, persistent archives, logic programming, and artificial intelligence. His latest projects include the Datanet Federation Consortium and DataBridge, building a social network platform for scientific data.",
    websitePath: "https://sils.unc.edu/people/faculty/profiles/Arcot-Rajasekar",
    linkText: "Personal Profile",
    websitePath1: "",
    linkText1: "",
    email: "sekar@renci.org",
    phone: "858-966-3611",
  },
  {
    id: 16,
    imgPath: "/Assets/Images/YueWang.jpeg",
    name: "Yue (Ray) Wang",
    text: "Dr. Yue Wang is interested in text data mining and machine learning with applications in health informatics. His dissertation focuses on developing principled interactive machine learning approaches that reduce human analysts' information processing workload. His work is motivated by and applied to various data mining problems, including high-recall information retrieval, clinical natural language processing, and qualitative content analysis. He publishes in both computer science and health informatics venues, including KDD, SIGIR, WSDM, and JAMIA. He and his collaborators won first place in the TREC 2013 Microblog Track, and he received the Best Paper Award and Outstanding Reviewer Award in WSDM 2016.",
    websitePath: "https://sils.unc.edu/people/faculty/profiles/Yue-Wang",
    linkText: "Button Text",
    websitePath1: "",
    linkText1: "Button Text2",
    email: "wangyue@email.unc.edu",
    phone: "919-966-5042",
  },
  {
    //done
    id: 17,
    imgPath: "/Assets/Images/HaoXu.jpeg",
    name: "Hao Xu",
    text: "Xu is a research scientist at the Renaissance Computing Institute, University of North Carolina at Chapel Hill. He co-developed the ICEES API and developed FHIR PIT. He worked on improving the rule engine and the rule language, and the metadata catalog of the integrated Rule-Oriented Data System (iRODS). He developed pluggable rule engine architecture that allows interoperability between different programming languages and the iRODS data management systems. He also developed QueryArrow, a semantically unified query and update system that allows bidirectional integration of metadata from multiple heterogeneous data stores. His research interests include theory of data management, automatic theorem proving, programming languages, distributed data systems, and formal methods in software development. He has a B.E. in computer science and engineering and a B.S. minor in applied mathematics from Beihang University and a Ph.D. in computer science from University of North Carolina at Chapel Hill.",
    websitePath:
      "https://renci.org/wp-content/uploads/2019/06/RENCI_201906_Photo_Xu_Hao.jpg",
    linkText: "Rencii Profile",
    websitePath1: "",
    linkText1: "Button Text2",
    email: "xuhao@renci.org",
    phone: "",
  },
];

export default CardData;
